auth:
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/contrib/social_auth_google/img/google_logo.svg
  social_auth_vk:
    route: social_auth_vk.redirect_to_vkontakte
    img_path: modules/contrib/social_auth_vk/img/vkontakte_logo.svg
post_login: /user
redirect_user_form: false
disable_admin_login: true
disabled_roles:
  administrator: '0'
user_allowed: register
_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
langcode: ru
